#' Add Synthetic Metrics to Season Summary Table
#'
#' Computes synthetic derived metrics used in the app,
#' including efficiencies, scores per entry, and ruck contest summaries.
#'
#' @param df A data frame produced by `SEASON_SUM_STATS2()`
#'
#' @return The same data frame with added synthetic metric columns
#' @export
add_in_app_synthetic_metrics <- function(df) {

  df %>%
    SEASON_SUM_STATS2() %>%
    mutate(KICK_EFFICIENCY = df$`EFFECTIVE KICK`/KICK,
           SCORES_PER_ENTRY = (GOAL+BEHIND+df$'RUSHED BEHIND')/df$'INSIDE 50',
           SHOT_AT_GOAL_ACCURACY = (GOAL/df$'SHOT AT GOAL'),
           BUTI_HITOUT = df$`BALL UP HITOUT`+ df$`THROW IN HITOUT`,
           BUTI_HITOUT_TO_ADV = df$`BU HITOUT TO ADVANTAGE`+ df$`TI HITOUT TO ADVANTAGE`,
           BUTI_HITOUT_SHARKED = df$`BALL UP HITOUT SHARKED`+ df$`THROW IN HITOUT SHARKED`,
           BUTI_FIRST_POSSESSION = df$`BALL UP FIRST POSSESSION`+ df$`THROW IN FIRST POSSESSION`,
           BUTI_CLEARANCE = df$`BALL UP CLEARANCE`+ df$`THROW IN CLEARANCE`) %>%

    mutate(KICK_EFFICIENCY_AG = df$`EFFECTIVE KICK_AG`/KICK_AG,
           SCORES_PER_ENTRY_AG = (GOAL_AG+BEHIND_AG+df$'RUSHED BEHIND_AG')/df$'INSIDE 50_AG',
           SHOT_AT_GOAL_ACCURACY_AG = (GOAL_AG/df$'SHOT AT GOAL_AG'),
           BUTI_HITOUT_AG = df$`BALL UP HITOUT_AG`+ df$`THROW IN HITOUT_AG`,
           BUTI_HITOUT_TO_ADV_AG = df$`BU HITOUT TO ADVANTAGE_AG`+ df$`TI HITOUT TO ADVANTAGE_AG`,
           BUTI_HITOUT_SHARKED_AG = df$`BALL UP HITOUT SHARKED_AG`+ df$`THROW IN HITOUT SHARKED_AG`,
           BUTI_FIRST_POSSESSION_AG = df$`BALL UP FIRST POSSESSION_AG`+ df$`THROW IN FIRST POSSESSION_AG`,
           BUTI_CLEARANCE_AG = df$`BALL UP CLEARANCE_AG`+ df$`THROW IN CLEARANCE_AG`) %>%


    mutate(PRESSURE_FACTOR             = PRESSURE_POINTS          / PRESSURE_CHANCES,
           PRE_CLR_PRESSURE_FACTOR     = PRE_CLR_PRESSURE_POINTS  / PRE_CLR_PRESSURE_CHANCES,
           POST_CLR_PRESSURE_FACTOR    = POST_CLR_PRESSURE_POINTS / POST_CLR_PRESSURE_CHANCES,
           D50_PRESSURE_FACTOR         = D50_PRESSURE_POINTS      / D50_PRESSURE_CHANCES,
           DM_PRESSURE_FACTOR          = DM_PRESSURE_POINTS       / DM_PRESSURE_CHANCES,
           AM_PRESSURE_FACTOR          = AM_PRESSURE_POINTS       / AM_PRESSURE_CHANCES,
           F50_PRESSURE_FACTOR         = F50_PRESSURE_POINTS      / F50_PRESSURE_CHANCES,
           FH_PRESSURE_FACTOR          = FH_PRESSURE_POINTS       / FH_PRESSURE_CHANCES,
           DH_PRESSURE_FACTOR          = DH_PRESSURE_POINTS       / DH_PRESSURE_CHANCES,
           CB_PRESSURE_FACTOR          = CB_PRESSURE_POINTS       / CB_PRESSURE_CHANCES,
           MCBU_PRESSURE_FACTOR        = MCBU_PRESSURE_POINTS     / MCBU_PRESSURE_CHANCES,
           M_TI_ST_PRESSURE_FACTOR     = M_TI_ST_PRESSURE_POINTS  / M_TI_ST_PRESSURE_CHANCES,
           M_BU_ST_PRESSURE_FACTOR     = M_BU_ST_PRESSURE_POINTS  / M_BU_ST_PRESSURE_CHANCES,
           WMBUTI_PRESSURE_FACTOR      = WMBUTI_PRESSURE_POINTS   / WMBUTI_PRESSURE_CHANCES,
           A5070_PRESSURE_FACTOR       = A5070_PRESSURE_POINTS    / A5070_PRESSURE_CHANCES,
           D5070_PRESSURE_FACTOR       = D5070_PRESSURE_POINTS    / D5070_PRESSURE_CHANCES,
           F50_ST_PRESSURE_FACTOR      = F50_ST_PRESSURE_POINTS   / F50_ST_PRESSURE_CHANCES,
           D50_ST_PRESSURE_FACTOR      = D50_ST_PRESSURE_POINTS   / D50_ST_PRESSURE_CHANCES,
           TO_TO_PRESSURE_FACTOR       = TO_TO_PRESSURE_POINTS    / TO_TO_PRESSURE_CHANCES,
           KI_TO_ST_PRESSURE_FACTOR    = KI_TO_PRESSURE_POINTS    / KI_TO_PRESSURE_CHANCES,
           KI_PRESSURE_FACTOR          = KI_PRESSURE_POINTS       / KI_PRESSURE_CHANCES,
           ST_POST_PRESSURE_CHANCES    = ST_POST_PRESSURE_POINTS  / ST_POST_PRESSURE_CHANCES,
           REPLY_PRESSURE_FACTOR       = REPLY_PRESSURE_POINTS    / REPLY_PRESSURE_CHANCES) %>%

    mutate(PRESSURE_FACTOR_AG             = PRESSURE_POINTS_AG          /PRESSURE_CHANCES_AG,
           PRE_CLR_PRESSURE_FACTOR_AG     = PRE_CLR_PRESSURE_POINTS_AG  /PRE_CLR_PRESSURE_CHANCES_AG,
           POST_CLR_PRESSURE_FACTOR_AG    = POST_CLR_PRESSURE_POINTS_AG /POST_CLR_PRESSURE_CHANCES_AG,
           D50_PRESSURE_FACTOR_AG         = D50_PRESSURE_POINTS_AG      /D50_PRESSURE_CHANCES_AG,
           DM_PRESSURE_FACTOR_AG          = DM_PRESSURE_POINTS_AG       /DM_PRESSURE_CHANCES_AG,
           AM_PRESSURE_FACTOR_AG          = AM_PRESSURE_POINTS_AG       /AM_PRESSURE_CHANCES_AG,
           F50_PRESSURE_FACTOR_AG         = F50_PRESSURE_POINTS_AG      /F50_PRESSURE_CHANCES_AG,
           FH_PRESSURE_FACTOR_AG          = FH_PRESSURE_POINTS_AG       /FH_PRESSURE_CHANCES_AG,
           DH_PRESSURE_FACTOR_AG          = DH_PRESSURE_POINTS_AG       /DH_PRESSURE_CHANCES_AG,
           CB_PRESSURE_FACTOR_AG          = CB_PRESSURE_POINTS_AG       /CB_PRESSURE_CHANCES_AG,
           MCBU_PRESSURE_FACTOR_AG        = MCBU_PRESSURE_POINTS_AG     /MCBU_PRESSURE_CHANCES_AG,
           M_TI_ST_PRESSURE_FACTOR_AG     = M_TI_ST_PRESSURE_POINTS_AG  /M_TI_ST_PRESSURE_CHANCES_AG,
           M_BU_ST_PRESSURE_FACTOR_AG     = M_BU_ST_PRESSURE_POINTS_AG  /M_BU_ST_PRESSURE_CHANCES_AG,
           WMBUTI_PRESSURE_FACTOR_AG      = WMBUTI_PRESSURE_POINTS_AG   /WMBUTI_PRESSURE_CHANCES_AG,
           A5070_PRESSURE_FACTOR_AG       = A5070_PRESSURE_POINTS_AG    /A5070_PRESSURE_CHANCES_AG,
           D5070_PRESSURE_FACTOR_AG       = D5070_PRESSURE_POINTS_AG    /D5070_PRESSURE_CHANCES_AG,
           F50_ST_PRESSURE_FACTOR_AG      = F50_ST_PRESSURE_POINTS_AG   /F50_ST_PRESSURE_CHANCES_AG,
           D50_ST_PRESSURE_FACTOR_AG      = D50_ST_PRESSURE_POINTS_AG   /D50_ST_PRESSURE_CHANCES_AG,
           TO_TO_PRESSURE_FACTOR_AG       = TO_TO_PRESSURE_POINTS_AG    / TO_TO_PRESSURE_CHANCES_AG,
           KI_TO_ST_PRESSURE_FACTOR_AG    = KI_TO_PRESSURE_POINTS_AG    / KI_TO_PRESSURE_CHANCES_AG,
           KI_PRESSURE_FACTOR_AG          = KI_PRESSURE_POINTS_AG       / KI_PRESSURE_CHANCES_AG,
           ST_POST_PRESSURE_CHANCES_AG    = ST_POST_PRESSURE_POINTS_AG  / ST_POST_PRESSURE_CHANCES_AG,
           REPLY_PRESSURE_FACTOR_AG       = REPLY_PRESSURE_POINTS_AG    / REPLY_PRESSURE_CHANCES_AG) %>%

    mutate (FAR_KICK_SCORING_RATE = FAR_KICK_SCORE/FAR_KICK,
            NEAR_KICK_SCORING_RATE = NEAR_KICK_SCORE/NEAR_KICK,
            DEEP_KICK_SCORING_RATE = DEEP_KICK_SCORE/DEEP_KICK,
            SHALLOW_KICK_SCORING_RATE = SHALLOW_KICK_SCORE/SHALLOW_KICK,
            FAR_DEEP_KICK_SCORING_RATE = FAR_DEEP_KICK_SCORE/FAR_DEEP_KICK,
            FAR_SHALLOW_KICK_SCORING_RATE = FAR_SHALLOW_KICK_SCORE/FAR_SHALLOW_KICK,
            NEAR_DEEP_KICK_SCORING_RATE = NEAR_DEEP_KICK_SCORE/NEAR_DEEP_KICK,
            NEAR_SHALLOW_KICK_SCORING_RATE = NEAR_SHALLOW_KICK_SCORE/NEAR_SHALLOW_KICK) %>%


    mutate (FAR_KICK_SCORING_RATE_AG = FAR_KICK_SCORE_AG/FAR_KICK_AG,
            NEAR_KICK_SCORING_RATE_AG = NEAR_KICK_SCORE_AG/NEAR_KICK_AG,
            DEEP_KICK_SCORING_RATE_AG = DEEP_KICK_SCORE_AG/DEEP_KICK_AG,
            SHALLOW_KICK_SCORING_RATE_AG = SHALLOW_KICK_SCORE_AG/SHALLOW_KICK_AG,
            FAR_DEEP_KICK_SCORING_RATE_AG = FAR_DEEP_KICK_SCORE_AG/FAR_DEEP_KICK_AG,
            FAR_SHALLOW_KICK_SCORING_RATE_AG = FAR_SHALLOW_KICK_SCORE_AG/FAR_SHALLOW_KICK_AG,
            NEAR_DEEP_KICK_SCORING_RATE_AG = NEAR_DEEP_KICK_SCORE_AG/NEAR_DEEP_KICK_AG,
            NEAR_SHALLOW_KICK_SCORING_RATE_AG = NEAR_SHALLOW_KICK_SCORE_AG/NEAR_SHALLOW_KICK_AG) %>%

    mutate (D50_ENT_DISP      = paste0(round((D50_INT_ENTRIES+D50_ST_ENTRIES+KI_ENTRIES)/(D50_INT_CHAINS+D50_ST_CHAINS+KI_CHAINS)*100,digits=0),"% (",(D50_INT_ENTRIES+D50_ST_ENTRIES+KI_ENTRIES),"/",(D50_INT_CHAINS+D50_ST_CHAINS+KI_CHAINS),")"),
            D50_SCR_DISP      = paste0((D50_INT_GOALS+D50_ST_GOALS+KI_GOALS),".",(D50_INT_BEHINDS+D50_ST_BEHINDS+KI_BEHINDS),".",(D50_INT_POINTS+D50_ST_POINTS+KI_POINTS)),
            D50_ENT_PERC      = round((D50_INT_ENTRIES+D50_ST_ENTRIES+KI_ENTRIES)/(D50_INT_CHAINS+D50_ST_CHAINS+KI_CHAINS)*100,digits=0),
            D50_SCR_PERC      = round((D50_INT_GOALS+D50_ST_GOALS+KI_GOALS+D50_INT_BEHINDS+D50_ST_BEHINDS+KI_BEHINDS)/(D50_INT_CHAINS+D50_ST_CHAINS+KI_CHAINS)*100,digits=0),

            D50_INT_ENT_DISP  = paste0(round(D50_INT_ENTRIES/D50_INT_CHAINS*100,digits=0),"% (",D50_INT_ENTRIES,"/",D50_INT_CHAINS,")"),
            D50_INT_SCR_DISP  = paste0(D50_INT_GOALS,".",D50_INT_BEHINDS,".",D50_INT_POINTS),
            D50_INT_ENT_PERC  = round((D50_INT_ENTRIES)/(D50_INT_CHAINS)*100,digits=0),
            D50_INT_SCR_PERC  = round((D50_INT_GOALS+D50_INT_BEHINDS)/(D50_INT_CHAINS)*100,digits=0),

            D50_ST_ENT_DISP   = paste0(round(D50_ST_ENTRIES/D50_ST_CHAINS*100,digits=0),"% (",D50_ST_ENTRIES,"/",D50_ST_CHAINS,")"),
            D50_ST_SCR_DISP   = paste0(D50_ST_GOALS,".",D50_ST_BEHINDS,".",D50_ST_POINTS),
            D50_ST_ENT_PERC   = round((D50_ST_ENTRIES)/(D50_ST_CHAINS)*100,digits=0),
            D50_ST_SCR_PERC   = round((D50_ST_GOALS+D50_ST_BEHINDS)/(D50_ST_CHAINS)*100,digits=0),

            D50_KI_ENT_DISP   = paste0(round(KI_ENTRIES/KI_CHAINS*100,digits=0),"% (",KI_ENTRIES,"/",KI_CHAINS,")"),
            D50_KI_SCR_DISP   = paste0(KI_GOALS,".",KI_BEHINDS,".",KI_POINTS),
            D50_KI_ENT_PERC   = round((KI_ENTRIES)/(KI_CHAINS)*100,digits=0),
            D50_KI_SCR_PERC   = round((KI_GOALS+KI_BEHINDS)/(KI_CHAINS)*100,digits=0),
            D50_KI_HW_PERC    = round((KI_HALFWAY)/(KI_CHAINS)*100,digits=0),
            D50_KI_TO_PERC    = round((KI_TO)/(KI_CHAINS)*100,digits=0),
            D50_KI_TO_PPKI    = round((KI_TO_POINTS)/(KI_CHAINS),digits=2),
            D50_KI_TO_SCR_PERC= round((KI_TO_SCORE)/(KI_CHAINS)*100,digits=0),

            DM_ENT_DISP       = paste0(round((DM_INT_ENTRIES+DM_ST_ENTRIES)/(DM_INT_CHAINS+DM_ST_CHAINS)*100,digits=0),"% (",(DM_INT_ENTRIES+DM_ST_ENTRIES),"/",(DM_INT_CHAINS+DM_ST_CHAINS),")"),
            DM_SCR_DISP       = paste0((DM_INT_GOALS+DM_ST_GOALS),".",(DM_INT_BEHINDS+DM_ST_BEHINDS),".",(DM_INT_POINTS+DM_ST_POINTS)),
            DM_ENT_PERC       = round((DM_INT_ENTRIES+DM_ST_ENTRIES)/(DM_INT_CHAINS+DM_ST_CHAINS)*100,digits=0),
            DM_SCR_PERC       = round((DM_INT_GOALS+DM_ST_GOALS+DM_INT_BEHINDS+DM_ST_BEHINDS)/(DM_INT_CHAINS+DM_ST_CHAINS)*100,digits=0),

            DM_INT_ENT_DISP   = paste0(round(DM_INT_ENTRIES/DM_INT_CHAINS*100,digits=0),"% (",DM_INT_ENTRIES,"/",DM_INT_CHAINS,")"),
            DM_INT_SCR_DISP   = paste0(DM_INT_GOALS,".",DM_INT_BEHINDS,".",DM_INT_POINTS),
            DM_INT_ENT_PERC   = round((DM_INT_ENTRIES)/(DM_INT_CHAINS)*100,digits=0),
            DM_INT_SCR_PERC   = round((DM_INT_GOALS+DM_INT_BEHINDS)/(DM_INT_CHAINS)*100,digits=0),

            DM_ST_ENT_DISP    = paste0(round(DM_ST_ENTRIES/DM_ST_CHAINS*100,digits=0),"% (",DM_ST_ENTRIES,"/",DM_ST_CHAINS,")"),
            DM_ST_SCR_DISP    = paste0(DM_ST_GOALS,".",DM_ST_BEHINDS,".",DM_ST_POINTS),
            DM_ST_ENT_PERC    = round((DM_ST_ENTRIES)/(DM_ST_CHAINS)*100,digits=0),
            DM_ST_SCR_PERC    = round((DM_ST_GOALS+DM_ST_BEHINDS)/(DM_ST_CHAINS)*100,digits=0),

            DH_ST_ENT_DISP    = paste0(round((DM_ST_ENTRIES+D50_ST_ENTRIES)/(DM_ST_CHAINS+D50_ST_CHAINS)*100,digits=0),"% (",(DM_ST_ENTRIES+D50_ST_ENTRIES),"/",(DM_ST_CHAINS+D50_ST_CHAINS),")"),
            DH_ST_SCR_DISP    = paste0((DM_ST_GOALS+D50_ST_GOALS),".",(DM_ST_BEHINDS+D50_ST_BEHINDS),".",(DM_ST_POINTS+D50_ST_POINTS)),
            DH_ST_ENT_PERC    = round((DM_ST_ENTRIES+D50_ST_ENTRIES)/(DM_ST_CHAINS+D50_ST_CHAINS)*100,digits=0),
            DH_ST_SCR_PERC    = round((DM_ST_GOALS+D50_ST_GOALS+DM_ST_BEHINDS+D50_ST_BEHINDS)/(DM_ST_CHAINS+D50_ST_CHAINS)*100,digits=0),

            CB_ENT_DISP       = paste0(round(CB_ENTRIES/CB_CHAINS*100,digits=0),"% (",CB_ENTRIES,"/",CB_CHAINS,")"),
            CB_SCR_DISP       = paste0(CB_GOALS,".",CB_BEHINDS,".",CB_POINTS),
            CB_ENT_PERC       = round((CB_ENTRIES)/(CB_CHAINS)*100,digits=0),
            CB_SCR_PERC       = round((CB_GOALS+CB_BEHINDS)/(CB_CHAINS)*100,digits=0),

            AM_ENT_DISP       = paste0(round((AM_INT_ENTRIES+AM_ST_ENTRIES)/(AM_INT_CHAINS+AM_ST_CHAINS)*100,digits=0),"% (",(AM_INT_ENTRIES+AM_ST_ENTRIES),"/",(AM_INT_CHAINS+AM_ST_CHAINS),")"),
            AM_SCR_DISP       = paste0((AM_INT_GOALS+AM_ST_GOALS),".",(AM_INT_BEHINDS+AM_ST_BEHINDS),".",(AM_INT_POINTS+AM_ST_POINTS)),
            AM_ENT_PERC       = round((AM_INT_ENTRIES+AM_ST_ENTRIES)/(AM_INT_CHAINS+AM_ST_CHAINS)*100,digits=0),
            AM_SCR_PERC       = round((AM_INT_GOALS+AM_ST_GOALS+AM_INT_BEHINDS+AM_ST_BEHINDS)/(AM_INT_CHAINS+AM_ST_CHAINS)*100,digits=0),

            AM_INT_ENT_DISP   = paste0(round(AM_INT_ENTRIES/AM_INT_CHAINS*100,digits=0),"% (",AM_INT_ENTRIES,"/",AM_INT_CHAINS,")"),
            AM_INT_SCR_DISP   = paste0(AM_INT_GOALS,".",AM_INT_BEHINDS,".",AM_INT_POINTS),
            AM_INT_ENT_PERC   = round((AM_INT_ENTRIES)/(AM_INT_CHAINS)*100,digits=0),
            AM_INT_SCR_PERC   = round((AM_INT_GOALS+AM_INT_BEHINDS)/(AM_INT_CHAINS)*100,digits=0),

            AM_ST_ENT_DISP    = paste0(round(AM_ST_ENTRIES/AM_ST_CHAINS*100,digits=0),"% (",AM_ST_ENTRIES,"/",AM_ST_CHAINS,")"),
            AM_ST_SCR_DISP    = paste0(AM_ST_GOALS,".",AM_ST_BEHINDS,".",AM_ST_POINTS),
            AM_ST_ENT_PERC    = round((AM_ST_ENTRIES)/(AM_ST_CHAINS)*100,digits=0),
            AM_ST_SCR_PERC    = round((AM_ST_GOALS+AM_ST_BEHINDS)/(AM_ST_CHAINS)*100,digits=0),

            F50_ENT_DISP      = paste0("-"),
            F50_SCR_DISP      = paste0((F50_INT_GOALS+F50_ST_GOALS),".",(F50_INT_BEHINDS+F50_ST_BEHINDS),".",(F50_INT_POINTS+F50_ST_POINTS)),
            F50_ENT_PERC      = paste0("-"),
            F50_SCR_PERC      = round((F50_INT_GOALS+F50_ST_GOALS+F50_INT_BEHINDS+F50_ST_BEHINDS)/(F50_INT_CHAINS+F50_ST_CHAINS)*100,digits=0),

            F50_INT_ENT_DISP  = paste0("-"),
            F50_INT_SCR_DISP  = paste0(F50_INT_GOALS,".",F50_INT_BEHINDS,".",F50_INT_POINTS),
            F50_INT_ENT_PERC  = paste0("-"),
            F50_INT_SCR_PERC  = round((F50_INT_GOALS+F50_INT_BEHINDS)/(F50_INT_CHAINS)*100,digits=0),

            F50_ST_ENT_DISP   = paste0("-"),
            F50_ST_SCR_DISP   = paste0(F50_ST_GOALS,".",F50_ST_BEHINDS,".",F50_ST_POINTS),
            F50_ST_ENT_PERC   = paste0("-"),
            F50_ST_SCR_PERC   = round((F50_ST_GOALS+F50_ST_BEHINDS)/(F50_ST_CHAINS)*100,digits=0),

            D50_SCR           = sum(D50_INT_POINTS,D50_ST_POINTS,KI_POINTS),
            DM_SCR            = sum(DM_INT_POINTS,DM_ST_POINTS),
            AM_SCR            = sum(AM_INT_POINTS,AM_ST_POINTS),
            F50_SCR           = sum(F50_INT_POINTS,F50_ST_POINTS),

            TACKLE_EFFICIENCY       = TACKLE       / (PHYSICAL_PRESSURE_CHANCES       + df$'MISSED TACKLES' + TACKLE_FREE_KICKS_AGST ),
            TACKLE_EFFICIENCY_PRE   = TACKLE_PRE   / (PHYSICAL_PRESSURE_CHANCES_PRE   + MISSED_TACKLE_PRE                    + TACKLE_FREE_KICKS_AGST_PRE ),
            TACKLE_EFFICIENCY_POST  = TACKLE_POST  / (PHYSICAL_PRESSURE_CHANCES_POST  + MISSED_TACKLE_POST                   + TACKLE_FREE_KICKS_AGST_POST ),

            CHALLENGE_ENT_DISP   = paste0(round(CHALLENGE_ENTRIES/CHALLENGE_CHAINS*100,digits=0),"% (",CHALLENGE_ENTRIES,"/",CHALLENGE_CHAINS,")"),
            CHALLENGE_SCR_DISP   = paste0(CHALLENGE_GOALS,".",CHALLENGE_BEHINDS,".",CHALLENGE_POINTS),
            CHALLENGE_ENT_PERC   = round((CHALLENGE_ENTRIES)/(CHALLENGE_CHAINS)*100,digits=0),
            CHALLENGE_SCR_PERC   = round((CHALLENGE_GOALS+CHALLENGE_BEHINDS)/(CHALLENGE_CHAINS)*100,digits=0),
            CHALLENGE_RETURN_SCR_DISP   = paste0(CHALLENGE_RETURN_GOALS,".",CHALLENGE_RETURN_BEHINDS,".",CHALLENGE_RETURN_POINTS),
            CHALLENGE_RETURN_SCR_PERC   = round((CHALLENGE_RETURN_GOALS+CHALLENGE_RETURN_BEHINDS)/(CHALLENGE_RETURN_CHAINS)*100,digits=0),
            CHALLENGE_RETURN_PERC    = round((CHALLENGE_RETURN_CHAINS)/(CHALLENGE_CHAINS)*100,digits=0),
            CHALLENGE_RETURN_PPKI    = round((CHALLENGE_RETURN_POINTS)/(CHALLENGE_CHAINS),digits=2),
            CHALLENGE_RETURN_SCR_PERC= round((CHALLENGE_RETURN_SCORES)/(CHALLENGE_CHAINS)*100,digits=0),

            CHOICE_ENT_DISP   = paste0(round(CHOICE_ENTRIES/CHOICE_CHAINS*100,digits=0),"% (",CHOICE_ENTRIES,"/",CHOICE_CHAINS,")"),
            CHOICE_SCR_DISP   = paste0(CHOICE_GOALS,".",CHOICE_BEHINDS,".",CHOICE_POINTS),
            CHOICE_ENT_PERC   = round((CHOICE_ENTRIES)/(CHOICE_CHAINS)*100,digits=0),
            CHOICE_SCR_PERC   = round((CHOICE_GOALS+CHOICE_BEHINDS)/(CHOICE_CHAINS)*100,digits=0),
            CHOICE_RETURN_SCR_DISP   = paste0(CHOICE_RETURN_GOALS,".",CHOICE_RETURN_BEHINDS,".",CHOICE_RETURN_POINTS),
            CHOICE_RETURN_SCR_PERC   = round((CHOICE_RETURN_GOALS+CHOICE_RETURN_BEHINDS)/(CHOICE_RETURN_CHAINS)*100,digits=0),
            CHOICE_RETURN_PERC    = round((CHOICE_RETURN_CHAINS)/(CHOICE_CHAINS)*100,digits=0),
            CHOICE_RETURN_PPKI    = round((CHOICE_RETURN_POINTS)/(CHOICE_CHAINS),digits=2),
            CHOICE_RETURN_SCR_PERC= round((CHOICE_RETURN_SCORES)/(CHOICE_CHAINS)*100,digits=0),

            CONTROL_ENT_DISP   = paste0(round(CONTROL_ENTRIES/CONTROL_CHAINS*100,digits=0),"% (",CONTROL_ENTRIES,"/",CONTROL_CHAINS,")"),
            CONTROL_SCR_DISP   = paste0(CONTROL_GOALS,".",CONTROL_BEHINDS,".",CONTROL_POINTS),
            CONTROL_ENT_PERC   = round((CONTROL_ENTRIES)/(CONTROL_CHAINS)*100,digits=0),
            CONTROL_SCR_PERC   = round((CONTROL_GOALS+CONTROL_BEHINDS)/(CONTROL_CHAINS)*100,digits=0),
            CONTROL_RETURN_SCR_DISP   = paste0(CONTROL_RETURN_GOALS,".",CONTROL_RETURN_BEHINDS,".",CONTROL_RETURN_POINTS),
            CONTROL_RETURN_SCR_PERC   = round((CONTROL_RETURN_GOALS+CONTROL_RETURN_BEHINDS)/(CONTROL_RETURN_CHAINS)*100,digits=0),
            CONTROL_RETURN_PERC    = round((CONTROL_RETURN_CHAINS)/(CONTROL_CHAINS)*100,digits=0),
            CONTROL_RETURN_PPKI    = round((CONTROL_RETURN_POINTS)/(CONTROL_CHAINS),digits=2),
            CONTROL_RETURN_SCR_PERC= round((CONTROL_RETURN_SCORES)/(CONTROL_CHAINS)*100,digits=0),

            LOCK_IN_RATE = LOCK_INS/ENTRIES,
            LOCK_IN_RATE_AG = LOCK_INS_AG/ENTRIES_AG) %>%


    mutate (D50_ENT_DISP_AG      = paste0(round((D50_INT_ENTRIES_AG+D50_ST_ENTRIES_AG+KI_ENTRIES_AG)/(D50_INT_CHAINS_AG+D50_ST_CHAINS_AG+KI_CHAINS_AG)*100,digits=0),"% (",(D50_INT_ENTRIES_AG+D50_ST_ENTRIES_AG+KI_ENTRIES_AG),"/",(D50_INT_CHAINS_AG+D50_ST_CHAINS_AG+KI_CHAINS_AG),")"),
            D50_SCR_DISP_AG      = paste0((D50_INT_GOALS_AG+D50_ST_GOALS_AG+KI_GOALS_AG),".",(D50_INT_BEHINDS_AG+D50_ST_BEHINDS_AG+KI_BEHINDS_AG),".",(D50_INT_POINTS_AG+D50_ST_POINTS_AG+KI_POINTS_AG)),
            D50_ENT_PERC_AG      = round((D50_INT_ENTRIES_AG+D50_ST_ENTRIES_AG+KI_ENTRIES_AG)/(D50_INT_CHAINS_AG+D50_ST_CHAINS_AG+KI_CHAINS_AG)*100,digits=0),
            D50_SCR_PERC_AG      = round((D50_INT_GOALS_AG+D50_ST_GOALS_AG+KI_GOALS_AG+D50_INT_BEHINDS_AG+D50_ST_BEHINDS_AG+KI_BEHINDS_AG)/(D50_INT_CHAINS_AG+D50_ST_CHAINS_AG+KI_CHAINS_AG)*100,digits=0),

            D50_INT_ENT_DISP_AG  = paste0(round(D50_INT_ENTRIES_AG/D50_INT_CHAINS_AG*100,digits=0),"% (",D50_INT_ENTRIES_AG,"/",D50_INT_CHAINS_AG,")"),
            D50_INT_SCR_DISP_AG  = paste0(D50_INT_GOALS_AG,".",D50_INT_BEHINDS_AG,".",D50_INT_POINTS_AG),
            D50_INT_ENT_PERC_AG  = round((D50_INT_ENTRIES_AG)/(D50_INT_CHAINS_AG)*100,digits=0),
            D50_INT_SCR_PERC_AG  = round((D50_INT_GOALS_AG+D50_INT_BEHINDS_AG)/(D50_INT_CHAINS_AG)*100,digits=0),

            D50_ST_ENT_DISP_AG   = paste0(round(D50_ST_ENTRIES_AG/D50_ST_CHAINS_AG*100,digits=0),"% (",D50_ST_ENTRIES_AG,"/",D50_ST_CHAINS_AG,")"),
            D50_ST_SCR_DISP_AG   = paste0(D50_ST_GOALS_AG,".",D50_ST_BEHINDS_AG,".",D50_ST_POINTS_AG),
            D50_ST_ENT_PERC_AG   = round((D50_ST_ENTRIES_AG)/(D50_ST_CHAINS_AG)*100,digits=0),
            D50_ST_SCR_PERC_AG   = round((D50_ST_GOALS_AG+D50_ST_BEHINDS_AG)/(D50_ST_CHAINS_AG)*100,digits=0),

            D50_KI_ENT_DISP_AG   = paste0(round(KI_ENTRIES_AG/KI_CHAINS_AG*100,digits=0),"% (",KI_ENTRIES_AG,"/",KI_CHAINS_AG,")"),
            D50_KI_SCR_DISP_AG   = paste0(KI_GOALS_AG,".",KI_BEHINDS_AG,".",KI_POINTS_AG),
            D50_KI_ENT_PERC_AG   = round((KI_ENTRIES_AG)/(KI_CHAINS_AG)*100,digits=0),
            D50_KI_SCR_PERC_AG   = round((KI_GOALS_AG+KI_BEHINDS_AG)/(KI_CHAINS_AG)*100,digits=0),
            D50_KI_HW_PERC_AG    = round((KI_HALFWAY_AG)/(KI_CHAINS_AG)*100,digits=0),
            D50_KI_TO_PERC_AG    = round((KI_TO_AG)/(KI_CHAINS_AG)*100,digits=0),
            D50_KI_TO_PPKI_AG    = round((KI_TO_POINTS_AG)/(KI_CHAINS_AG),digits=2),
            D50_KI_TO_SCR_PERC_AG= round((KI_TO_SCORE_AG)/(KI_CHAINS_AG)*100,digits=0),

            DM_ENT_DISP_AG       = paste0(round((DM_INT_ENTRIES_AG+DM_ST_ENTRIES_AG)/(DM_INT_CHAINS_AG+DM_ST_CHAINS_AG)*100,digits=0),"% (",(DM_INT_ENTRIES_AG+DM_ST_ENTRIES_AG),"/",(DM_INT_CHAINS_AG+DM_ST_CHAINS_AG),")"),
            DM_SCR_DISP_AG       = paste0((DM_INT_GOALS_AG+DM_ST_GOALS_AG),".",(DM_INT_BEHINDS_AG+DM_ST_BEHINDS_AG),".",(DM_INT_POINTS_AG+DM_ST_POINTS_AG)),
            DM_ENT_PERC_AG       = round((DM_INT_ENTRIES_AG+DM_ST_ENTRIES_AG)/(DM_INT_CHAINS_AG+DM_ST_CHAINS_AG)*100,digits=0),
            DM_SCR_PERC_AG       = round((DM_INT_GOALS_AG+DM_ST_GOALS_AG+DM_INT_BEHINDS_AG+DM_ST_BEHINDS_AG)/(DM_INT_CHAINS_AG+DM_ST_CHAINS_AG)*100,digits=0),

            DM_INT_ENT_DISP_AG   = paste0(round(DM_INT_ENTRIES_AG/DM_INT_CHAINS_AG*100,digits=0),"% (",DM_INT_ENTRIES_AG,"/",DM_INT_CHAINS_AG,")"),
            DM_INT_SCR_DISP_AG   = paste0(DM_INT_GOALS_AG,".",DM_INT_BEHINDS_AG,".",DM_INT_POINTS_AG),
            DM_INT_ENT_PERC_AG   = round((DM_INT_ENTRIES_AG)/(DM_INT_CHAINS_AG)*100,digits=0),
            DM_INT_SCR_PERC_AG   = round((DM_INT_GOALS_AG+DM_INT_BEHINDS_AG)/(DM_INT_CHAINS_AG)*100,digits=0),

            DM_ST_ENT_DISP_AG    = paste0(round(DM_ST_ENTRIES_AG/DM_ST_CHAINS_AG*100,digits=0),"% (",DM_ST_ENTRIES_AG,"/",DM_ST_CHAINS_AG,")"),
            DM_ST_SCR_DISP_AG    = paste0(DM_ST_GOALS_AG,".",DM_ST_BEHINDS_AG,".",DM_ST_POINTS_AG),
            DM_ST_ENT_PERC_AG    = round((DM_ST_ENTRIES_AG)/(DM_ST_CHAINS_AG)*100,digits=0),
            DM_ST_SCR_PERC_AG    = round((DM_ST_GOALS_AG+DM_ST_BEHINDS_AG)/(DM_ST_CHAINS_AG)*100,digits=0),

            DH_ST_ENT_DISP_AG    = paste0(round((DM_ST_ENTRIES_AG+D50_ST_ENTRIES_AG)/(DM_ST_CHAINS_AG+D50_ST_CHAINS_AG)*100,digits=0),"% (",(DM_ST_ENTRIES_AG+D50_ST_ENTRIES_AG),"/",(DM_ST_CHAINS_AG+D50_ST_CHAINS_AG),")"),
            DH_ST_SCR_DISP_AG    = paste0((DM_ST_GOALS_AG+D50_ST_GOALS_AG),".",(DM_ST_BEHINDS_AG+D50_ST_BEHINDS_AG),".",(DM_ST_POINTS_AG+D50_ST_POINTS_AG)),
            DH_ST_ENT_PERC_AG    = round((DM_ST_ENTRIES_AG+D50_ST_ENTRIES_AG)/(DM_ST_CHAINS_AG+D50_ST_CHAINS_AG)*100,digits=0),
            DH_ST_SCR_PERC_AG    = round((DM_ST_GOALS_AG+D50_ST_GOALS_AG+DM_ST_BEHINDS_AG+D50_ST_BEHINDS_AG)/(DM_ST_CHAINS_AG+D50_ST_CHAINS_AG)*100,digits=0),

            CB_ENT_DISP_AG       = paste0(round(CB_ENTRIES_AG/CB_CHAINS_AG*100,digits=0),"% (",CB_ENTRIES_AG,"/",CB_CHAINS_AG,")"),
            CB_SCR_DISP_AG       = paste0(CB_GOALS_AG,".",CB_BEHINDS_AG,".",CB_POINTS_AG),
            CB_ENT_PERC_AG       = round((CB_ENTRIES_AG)/(CB_CHAINS_AG)*100,digits=0),
            CB_SCR_PERC_AG       = round((CB_GOALS_AG+CB_BEHINDS_AG)/(CB_CHAINS_AG)*100,digits=0),

            AM_ENT_DISP_AG       = paste0(round((AM_INT_ENTRIES_AG+AM_ST_ENTRIES_AG)/(AM_INT_CHAINS_AG+AM_ST_CHAINS_AG)*100,digits=0),"% (",(AM_INT_ENTRIES_AG+AM_ST_ENTRIES_AG),"/",(AM_INT_CHAINS_AG+AM_ST_CHAINS_AG),")"),
            AM_SCR_DISP_AG       = paste0((AM_INT_GOALS_AG+AM_ST_GOALS_AG),".",(AM_INT_BEHINDS_AG+AM_ST_BEHINDS_AG),".",(AM_INT_POINTS_AG+AM_ST_POINTS_AG)),
            AM_ENT_PERC_AG       = round((AM_INT_ENTRIES_AG+AM_ST_ENTRIES_AG)/(AM_INT_CHAINS_AG+AM_ST_CHAINS_AG)*100,digits=0),
            AM_SCR_PERC_AG       = round((AM_INT_GOALS_AG+AM_ST_GOALS_AG+AM_INT_BEHINDS_AG+AM_ST_BEHINDS_AG)/(AM_INT_CHAINS_AG+AM_ST_CHAINS_AG)*100,digits=0),

            AM_INT_ENT_DISP_AG   = paste0(round(AM_INT_ENTRIES_AG/AM_INT_CHAINS_AG*100,digits=0),"% (",AM_INT_ENTRIES_AG,"/",AM_INT_CHAINS_AG,")"),
            AM_INT_SCR_DISP_AG   = paste0(AM_INT_GOALS_AG,".",AM_INT_BEHINDS_AG,".",AM_INT_POINTS_AG),
            AM_INT_ENT_PERC_AG   = round((AM_INT_ENTRIES_AG)/(AM_INT_CHAINS_AG)*100,digits=0),
            AM_INT_SCR_PERC_AG   = round((AM_INT_GOALS_AG+AM_INT_BEHINDS_AG)/(AM_INT_CHAINS_AG)*100,digits=0),

            AM_ST_ENT_DISP_AG    = paste0(round(AM_ST_ENTRIES_AG/AM_ST_CHAINS_AG*100,digits=0),"% (",AM_ST_ENTRIES_AG,"/",AM_ST_CHAINS_AG,")"),
            AM_ST_SCR_DISP_AG    = paste0(AM_ST_GOALS_AG,".",AM_ST_BEHINDS_AG,".",AM_ST_POINTS_AG),
            AM_ST_ENT_PERC_AG    = round((AM_ST_ENTRIES_AG)/(AM_ST_CHAINS_AG)*100,digits=0),
            AM_ST_SCR_PERC_AG    = round((AM_ST_GOALS_AG+AM_ST_BEHINDS_AG)/(AM_ST_CHAINS_AG)*100,digits=0),

            F50_ENT_DISP_AG      = paste0("-"),
            F50_SCR_DISP_AG      = paste0((F50_INT_GOALS_AG+F50_ST_GOALS_AG),".",(F50_INT_BEHINDS_AG+F50_ST_BEHINDS_AG),".",(F50_INT_POINTS_AG+F50_ST_POINTS_AG)),
            F50_ENT_PERC_AG      = paste0("-"),
            F50_SCR_PERC_AG      = round((F50_INT_GOALS_AG+F50_ST_GOALS_AG+F50_INT_BEHINDS_AG+F50_ST_BEHINDS_AG)/(F50_INT_CHAINS_AG+F50_ST_CHAINS_AG)*100,digits=0),

            F50_INT_ENT_DISP_AG  = paste0("-"),
            F50_INT_SCR_DISP_AG  = paste0(F50_INT_GOALS_AG,".",F50_INT_BEHINDS_AG,".",F50_INT_POINTS_AG),
            F50_INT_ENT_PERC_AG  = paste0("-"),
            F50_INT_SCR_PERC_AG  = round((F50_INT_GOALS_AG+F50_INT_BEHINDS_AG)/(F50_INT_CHAINS_AG)*100,digits=0),

            F50_ST_ENT_DISP_AG   = paste0("-"),
            F50_ST_SCR_DISP_AG   = paste0(F50_ST_GOALS_AG,".",F50_ST_BEHINDS_AG,".",F50_ST_POINTS_AG),
            F50_ST_ENT_PERC_AG   = paste0("-"),
            F50_ST_SCR_PERC_AG   = round((F50_ST_GOALS_AG+F50_ST_BEHINDS_AG)/(F50_ST_CHAINS_AG)*100,digits=0),

            D50_SCR_AG           = sum(D50_INT_POINTS_AG,D50_ST_POINTS_AG,KI_POINTS_AG),
            DM_SCR_AG            = sum(DM_INT_POINTS_AG,DM_ST_POINTS_AG),
            AM_SCR_AG            = sum(AM_INT_POINTS_AG,AM_ST_POINTS_AG),
            F50_SCR_AG           = sum(F50_INT_POINTS_AG,F50_ST_POINTS_AG),
            TACKLE_EFFICIENCY_AG      = TACKLE_AG       / (PHYSICAL_PRESSURE_CHANCES_AG       + df$'MISSED TACKLES_AG' + TACKLE_FREE_KICKS_AGST_AG ),
            TACKLE_EFFICIENCY_PRE_AG   = TACKLE_PRE_AG   / (PHYSICAL_PRESSURE_CHANCES_PRE_AG   + MISSED_TACKLE_PRE_AG                   + TACKLE_FREE_KICKS_AGST_PRE_AG ),
            TACKLE_EFFICIENCY_POST_AG  = TACKLE_POST_AG  / (PHYSICAL_PRESSURE_CHANCES_POST_AG  + MISSED_TACKLE_POST_AG                  + TACKLE_FREE_KICKS_AGST_POST_AG ),

            CHALLENGE_ENT_DISP_AG   = paste0(round(CHALLENGE_ENTRIES_AG/CHALLENGE_CHAINS_AG*100,digits=0),"% (",CHALLENGE_ENTRIES_AG,"/",CHALLENGE_CHAINS_AG,")"),
            CHALLENGE_SCR_DISP_AG   = paste0(CHALLENGE_GOALS_AG,".",CHALLENGE_BEHINDS_AG,".",CHALLENGE_POINTS_AG),
            CHALLENGE_ENT_PERC_AG   = round((CHALLENGE_ENTRIES_AG)/(CHALLENGE_CHAINS_AG)*100,digits=0),
            CHALLENGE_SCR_PERC_AG   = round((CHALLENGE_GOALS_AG+CHALLENGE_BEHINDS_AG)/(CHALLENGE_CHAINS_AG)*100,digits=0),
            CHALLENGE_RETURN_SCR_DISP_AG   = paste0(CHALLENGE_RETURN_GOALS_AG,".",CHALLENGE_RETURN_BEHINDS_AG,".",CHALLENGE_RETURN_POINTS_AG),
            CHALLENGE_RETURN_SCR_PERC_AG   = round((CHALLENGE_RETURN_GOALS_AG+CHALLENGE_RETURN_BEHINDS_AG)/(CHALLENGE_RETURN_CHAINS_AG)*100,digits=0),
            CHALLENGE_RETURN_PERC_AG     = round((CHALLENGE_RETURN_CHAINS_AG)/(CHALLENGE_CHAINS_AG)*100,digits=0),
            CHALLENGE_RETURN_PPKI_AG     = round((CHALLENGE_RETURN_POINTS_AG)/(CHALLENGE_CHAINS_AG),digits=2),
            CHALLENGE_RETURN_SCR_PERC_AG = round((CHALLENGE_RETURN_SCORES_AG)/(CHALLENGE_CHAINS_AG)*100,digits=0),

            CHOICE_ENT_DISP_AG   = paste0(round(CHOICE_ENTRIES_AG/CHOICE_CHAINS_AG*100,digits=0),"% (",CHOICE_ENTRIES_AG,"/",CHOICE_CHAINS_AG,")"),
            CHOICE_SCR_DISP_AG   = paste0(CHOICE_GOALS_AG,".",CHOICE_BEHINDS_AG,".",CHOICE_POINTS_AG),
            CHOICE_ENT_PERC_AG   = round((CHOICE_ENTRIES_AG)/(CHOICE_CHAINS_AG)*100,digits=0),
            CHOICE_SCR_PERC_AG   = round((CHOICE_GOALS_AG+CHOICE_BEHINDS_AG)/(CHOICE_CHAINS_AG)*100,digits=0),
            CHOICE_RETURN_SCR_DISP_AG   = paste0(CHOICE_RETURN_GOALS_AG,".",CHOICE_RETURN_BEHINDS_AG,".",CHOICE_RETURN_POINTS_AG),
            CHOICE_RETURN_SCR_PERC_AG   = round((CHOICE_RETURN_GOALS_AG+CHOICE_RETURN_BEHINDS_AG)/(CHOICE_RETURN_CHAINS_AG)*100,digits=0),
            CHOICE_RETURN_PERC_AG    = round((CHOICE_RETURN_CHAINS_AG)/(CHOICE_CHAINS_AG)*100,digits=0),
            CHOICE_RETURN_PPKI_AG    = round((CHOICE_RETURN_POINTS_AG)/(CHOICE_CHAINS_AG),digits=2),
            CHOICE_RETURN_SCR_PERC_AG= round((CHOICE_RETURN_SCORES_AG)/(CHOICE_CHAINS_AG)*100,digits=0),

            CONTROL_ENT_DISP_AG   = paste0(round(CONTROL_ENTRIES_AG/CONTROL_CHAINS_AG*100,digits=0),"% (",CONTROL_ENTRIES_AG,"/",CONTROL_CHAINS_AG,")"),
            CONTROL_SCR_DISP_AG   = paste0(CONTROL_GOALS_AG,".",CONTROL_BEHINDS_AG,".",CONTROL_POINTS_AG),
            CONTROL_ENT_PERC_AG   = round((CONTROL_ENTRIES_AG)/(CONTROL_CHAINS_AG)*100,digits=0),
            CONTROL_SCR_PERC_AG   = round((CONTROL_GOALS_AG+CONTROL_BEHINDS_AG)/(CONTROL_CHAINS_AG)*100,digits=0),
            CONTROL_RETURN_SCR_DISP_AG   = paste0(CONTROL_RETURN_GOALS_AG,".",CONTROL_RETURN_BEHINDS_AG,".",CONTROL_RETURN_POINTS_AG),
            CONTROL_RETURN_SCR_PERC_AG   = round((CONTROL_RETURN_GOALS_AG+CONTROL_RETURN_BEHINDS_AG)/(CONTROL_RETURN_CHAINS_AG)*100,digits=0),
            CONTROL_RETURN_PERC_AG    = round((CONTROL_RETURN_CHAINS_AG)/(CONTROL_CHAINS_AG)*100,digits=0),
            CONTROL_RETURN_PPKI_AG    = round((CONTROL_RETURN_POINTS_AG)/(CONTROL_CHAINS_AG),digits=2),
            CONTROL_RETURN_SCR_PERC_AG= round((CONTROL_RETURN_SCORES_AG)/(CONTROL_CHAINS_AG)*100,digits=0),

            TRANSITION_SPEED  = TRANSITION_SECS/TRANSITION,
            TRANSITION_SPEED_AG = TRANSITION_SECS_AG/TRANSITION_AG,

            CORRIDOR_EXIT_RATE = CORRIDOR_EXIT/(CORRIDOR_EXIT+WING_EXIT+BOUNDARY_EXIT),
            WING_EXIT_RATE = WING_EXIT/(CORRIDOR_EXIT+WING_EXIT+BOUNDARY_EXIT),
            BOUNDARY_EXIT_RATE = BOUNDARY_EXIT/(CORRIDOR_EXIT+WING_EXIT+BOUNDARY_EXIT),
            CORRIDOR_EXIT_RATE_AG = CORRIDOR_EXIT_AG/(CORRIDOR_EXIT_AG+WING_EXIT_AG+BOUNDARY_EXIT_AG),
            WING_EXIT_RATE_AG = WING_EXIT_AG/(CORRIDOR_EXIT_AG+WING_EXIT_AG+BOUNDARY_EXIT_AG),
            BOUNDARY_EXIT_RATE_AG = BOUNDARY_EXIT_AG/(CORRIDOR_EXIT_AG+WING_EXIT_AG+BOUNDARY_EXIT_AG),

            OLDL_WIN_RATE = (LDL_Retained/LDL),
            OLDL_LOSS_RATE  = (LDL_Lost/LDL),
            OLDL_SCORE_RATE  = (LDL_Score/LDL),
            OLDL_TO_SCORE_RATE  = (LDL_Lost_Score/LDL),

            OLDL_WIN_RATE_O30 = (LDL_Retained_O30/LDL_O30),
            OLDL_LOSS_RATE_O30  = (LDL_Lost_O30/LDL_O30),
            OLDL_SCORE_RATE_O30  = (LDL_Score_O30/LDL_O30),
            OLDL_TO_SCORE_RATE_O30  = (LDL_Lost_Score_O30/LDL_O30),

            OLDL_WIN_RATE_D30 = (LDL_Retained_D30/LDL_D30),
            OLDL_LOSS_RATE_D30  = (LDL_Lost_D30/LDL_D30),
            OLDL_SCORE_RATE_D30  = (LDL_Score_D30/LDL_D30),
            OLDL_TO_SCORE_RATE_D30  = (LDL_Lost_Score_D30/LDL_D30),

            OLDL_WIN_RATE_AG = (LDL_Retained_AG/LDL_AG),
            OLDL_LOSS_RATE_AG  = (LDL_Lost_AG/LDL_AG),
            OLDL_SCORE_RATE_AG  = (LDL_Score_AG/LDL_AG),
            OLDL_TO_SCORE_RATE_AG  = (LDL_Lost_Score_AG/LDL_AG),

            OLDL_WIN_RATE_O30_AG = (LDL_Retained_O30_AG/LDL_O30_AG),
            OLDL_LOSS_RATE_O30_AG  = (LDL_Lost_O30_AG/LDL_O30_AG),
            OLDL_SCORE_RATE_O30_AG  = (LDL_Score_O30_AG/LDL_O30_AG),
            OLDL_TO_SCORE_RATE_O30_AG  = (LDL_Lost_Score_O30_AG/LDL_O30_AG),

            OLDL_WIN_RATE_D30_AG = (LDL_Retained_D30_AG/LDL_D30_AG),
            OLDL_LOSS_RATE_D30_AG  = (LDL_Lost_D30_AG/LDL_D30_AG),
            OLDL_SCORE_RATE_D30_AG  = (LDL_Score_D30_AG/LDL_D30_AG),
            OLDL_TO_SCORE_RATE_D30_AG  = (LDL_Lost_Score_D30_AG/LDL_D30_AG),

            SWITCH_INSIDE_50_RATE = (switch.entry/switch),
            SWITCH_SCORE_RATE  = (switch.score/switch),
            SWITCH_TURNOVER_SCORE_RATE  = (switch.turnover.score/switch),

            FORTYFIVE_RETENTION_RATE = (fortyfive.retained / fortyfive),
            FORTYFIVE_SCORING_RATE = (fortyfive.score / fortyfive),
            FORTYFIVE_TURNOVER_RATE = (fortyfive.lost / fortyfive),
            FORTYFIVE_TURNOVER_SCORING_RATE = (fortyfive.lost.score / fortyfive),

            SWITCH_INSIDE_50_RATE_AG = (switch.entry_AG/switch_AG),
            SWITCH_SCORE_RATE_AG  = (switch.score_AG/switch_AG),
            SWITCH_TURNOVER_SCORE_RATE_AG  = (switch.turnover.score_AG/switch_AG),

            FORTYFIVE_RETENTION_RATE_AG = (fortyfive.retained_AG / fortyfive_AG),
            FORTYFIVE_SCORING_RATE_AG = (fortyfive.score_AG / fortyfive_AG),
            FORTYFIVE_TURNOVER_RATE_AG = (fortyfive.lost_AG / fortyfive_AG),
            FORTYFIVE_TURNOVER_SCORING_RATE_AG = (fortyfive.lost.score_AG / fortyfive_AG),

            REBOUND_50_STOP_RATE = (REBOUND_50_STOP/REBOUND_50),
            REBOUND_50_STOP_ST_RATE = (REBOUND_50_STOP_ST/REBOUND_50),
            REBOUND_50_STOP_TO_RATE = (REBOUND_50_STOP_INT/REBOUND_50),

            REBOUND_50_STOP_RATE_AG = (REBOUND_50_STOP_AG/REBOUND_50_AG),
            REBOUND_50_STOP_ST_RATE_AG = (REBOUND_50_STOP_ST_AG/REBOUND_50_AG),
            REBOUND_50_STOP_TO_RATE_AG = (REBOUND_50_STOP_INT_AG/REBOUND_50_AG),

            D5070_CHAIN_METRE_AVE = (D5070_ST_CHAIN_METRES / D5070_ST_CHAINS),
            D5070_REPLY_METRE_AVE = ((D5070_ST_REPLY_METRES) / D5070_REPLY_CHAINS),
            D5070_REPLY_REPLY_METRE_AVE = (D5070_REPLY_REPLY_CHAIN_METRES / D5070_REPLY_REPLY_CHAINS),

            D5070_CHAIN_METRE_AVE_AG =       ( D5070_ST_CHAIN_METRES_AG / D5070_ST_CHAINS_AG),
            D5070_REPLY_METRE_AVE_AG =       ((D5070_ST_REPLY_METRES_AG) / D5070_REPLY_CHAINS_AG),
            D5070_REPLY_REPLY_METRE_AVE_AG = ( D5070_REPLY_REPLY_CHAIN_METRES_AG / D5070_REPLY_REPLY_CHAINS_AG),

            A5070_CHAIN_METRE_AVE = (A5070_ST_CHAIN_METRES / A5070_ST_CHAINS),
            A5070_REPLY_METRE_AVE = ((A5070_ST_REPLY_METRES) / A5070_REPLY_CHAINS),
            A5070_REPLY_REPLY_METRE_AVE = (A5070_REPLY_REPLY_CHAIN_METRES / A5070_REPLY_REPLY_CHAINS),

            A5070_CHAIN_METRE_AVE_AG =       (A5070_ST_CHAIN_METRES_AG / A5070_ST_CHAINS_AG),
            A5070_REPLY_METRE_AVE_AG =       ((A5070_ST_REPLY_METRES_AG) / A5070_REPLY_CHAINS_AG),
            A5070_REPLY_REPLY_METRE_AVE_AG = ( A5070_REPLY_REPLY_CHAIN_METRES_AG / A5070_REPLY_REPLY_CHAINS_AG),

            ST_CHAIN_M_AVE = (ST_CHAIN_METRES/ST_CHAINS),
            ST_REPLY_M_AVE = (ST_REPLY_METRES/ST_REPLY_CHAINS),
            ST_CHAIN_M_AVE_AG = (ST_CHAIN_METRES_AG/ST_CHAINS_AG),
            ST_REPLY_M_AVE_AG = (ST_REPLY_METRES_AG/ST_REPLY_CHAINS_AG),

            ST_CHAIN_M_AVE1 = (ST_CHAIN_METRES/ST_CHAINS),
            ST_REPLY_M_AVE1 = (ST_REPLY_METRES/ST_REPLY_CHAINS),
            ST_CHAIN_M_AVE1_AG = (ST_CHAIN_METRES_AG/ST_CHAINS_AG),
            ST_REPLY_M_AVE1_AG = (ST_REPLY_METRES_AG/ST_REPLY_CHAINS_AG),

            F50_ST_CHAIN_M_AVE = (F50_ST_CHAIN_METRES/F50_ST_CHAINS),
            F50_ST_REPLY_M_AVE = (F50_ST_REPLY_METRES/F50_ST_REPLY_CHAINS),
            F50_ST_CHAIN_M_AVE_AG = (F50_ST_CHAIN_METRES_AG/F50_ST_CHAINS_AG),
            F50_ST_REPLY_M_AVE_AG = (F50_ST_REPLY_METRES_AG/F50_ST_REPLY_CHAINS_AG),

            AM_ST_CHAIN_M_AVE = (AM_ST_CHAIN_METRES/AM_ST_CHAINS),
            AM_ST_REPLY_M_AVE = (AM_ST_REPLY_METRES/AM_ST_REPLY_CHAINS),
            AM_ST_CHAIN_M_AVE_AG = (AM_ST_CHAIN_METRES_AG/AM_ST_CHAINS_AG),
            AM_ST_REPLY_M_AVE_AG = (AM_ST_REPLY_METRES_AG/AM_ST_REPLY_CHAINS_AG),

            DM_ST_CHAIN_M_AVE = (DM_ST_CHAIN_METRES/DM_ST_CHAINS),
            DM_ST_REPLY_M_AVE = (DM_ST_REPLY_METRES/DM_ST_REPLY_CHAINS),
            DM_ST_CHAIN_M_AVE_AG = (DM_ST_CHAIN_METRES_AG/DM_ST_CHAINS_AG),
            DM_ST_REPLY_M_AVE_AG = (DM_ST_REPLY_METRES_AG/DM_ST_REPLY_CHAINS_AG),

            D50_ST_CHAIN_M_AVE = (D50_ST_CHAIN_METRES/D50_ST_CHAINS),
            D50_ST_REPLY_M_AVE = (D50_ST_REPLY_METRES/D50_ST_REPLY_CHAINS),
            D50_ST_CHAIN_M_AVE_AG = (D50_ST_CHAIN_METRES_AG/D50_ST_CHAINS_AG),
            D50_ST_REPLY_M_AVE_AG = (D50_ST_REPLY_METRES_AG/D50_ST_REPLY_CHAINS_AG),

            KI_CHAIN_M_AVE = (KI_CHAIN_METRES/KI_CHAINS),
            KI_REPLY_M_AVE = (KI_REPLY_METRES/KI_REPLY_CHAINS),
            KI_CHAIN_M_AVE_AG = (KI_CHAIN_METRES_AG/KI_CHAINS_AG),
            KI_REPLY_M_AVE_AG = (KI_REPLY_METRES_AG/KI_REPLY_CHAINS_AG),

            M_BU_ST_CHAIN_M_AVE = (M_BU_ST_CHAIN_METRES/M_BU_ST_CHAINS),
            M_BU_ST_REPLY_M_AVE = (M_BU_ST_REPLY_METRES/M_BU_ST_REPLY_CHAINS),
            M_BU_ST_CHAIN_M_AVE_AG = (M_BU_ST_CHAIN_METRES_AG/M_BU_ST_CHAINS_AG),
            M_BU_ST_REPLY_M_AVE_AG = (M_BU_ST_REPLY_METRES_AG/M_BU_ST_REPLY_CHAINS_AG),

            M_TI_ST_CHAIN_M_AVE = (M_TI_ST_CHAIN_METRES/M_TI_ST_CHAINS),
            M_TI_ST_REPLY_M_AVE = (M_TI_ST_REPLY_METRES/M_TI_ST_REPLY_CHAINS),
            M_TI_ST_CHAIN_M_AVE_AG = (M_TI_ST_CHAIN_METRES_AG/M_TI_ST_CHAINS_AG),
            M_TI_ST_REPLY_M_AVE_AG = (M_TI_ST_REPLY_METRES_AG/M_TI_ST_REPLY_CHAINS_AG),

            CB_CHAIN_M_AVE = (CB_CHAIN_METRES/CB_CHAINS),
            CB_REPLY_M_AVE = (CB_REPLY_METRES/CB_REPLY_CHAINS),
            CB_CHAIN_M_AVE_AG = (CB_CHAIN_METRES_AG/CB_CHAINS_AG),
            CB_REPLY_M_AVE_AG = (CB_REPLY_METRES_AG/CB_REPLY_CHAINS_AG),

            CB_CHAIN_M_AVE1 = (CB_CHAIN_METRES/CB_CHAINS),
            CB_REPLY_M_AVE1 = (CB_REPLY_METRES/CB_REPLY_CHAINS),
            CB_CHAIN_M_AVE1_AG = (CB_CHAIN_METRES_AG/CB_CHAINS_AG),
            CB_REPLY_M_AVE1_AG = (CB_REPLY_METRES_AG/CB_REPLY_CHAINS_AG),

            M_BU_ST_CHAIN_M_AVE = (M_BU_ST_CHAIN_METRES/M_BU_ST_CHAINS),
            M_BU_ST_REPLY_M_AVE = (M_BU_ST_REPLY_METRES/M_BU_ST_REPLY_CHAINS),
            M_BU_ST_CHAIN_M_AVE_AG = (M_BU_ST_CHAIN_METRES_AG/M_BU_ST_CHAINS_AG),
            M_BU_ST_REPLY_M_AVE_AG = (M_BU_ST_REPLY_METRES_AG/M_BU_ST_REPLY_CHAINS_AG),

            M_BU_ST_CHAIN_M_AVE1 = (M_BU_ST_CHAIN_METRES/M_BU_ST_CHAINS),
            M_BU_ST_REPLY_M_AVE1 = (M_BU_ST_REPLY_METRES/M_BU_ST_REPLY_CHAINS),
            M_BU_ST_CHAIN_M_AVE1_AG = (M_BU_ST_CHAIN_METRES_AG/M_BU_ST_CHAINS_AG),
            M_BU_ST_REPLY_M_AVE1_AG = (M_BU_ST_REPLY_METRES_AG/M_BU_ST_REPLY_CHAINS_AG),

            M_TI_ST_CHAIN_M_AVE = (M_TI_ST_CHAIN_METRES/M_TI_ST_CHAINS),
            M_TI_ST_REPLY_M_AVE = (M_TI_ST_REPLY_METRES/M_TI_ST_REPLY_CHAINS),
            M_TI_ST_CHAIN_M_AVE_AG = (M_TI_ST_CHAIN_METRES_AG/M_TI_ST_CHAINS_AG),
            M_TI_ST_REPLY_M_AVE_AG = (M_TI_ST_REPLY_METRES_AG/M_TI_ST_REPLY_CHAINS_AG),

            M_TI_ST_CHAIN_M_AVE1 = (M_TI_ST_CHAIN_METRES/M_TI_ST_CHAINS),
            M_TI_ST_REPLY_M_AVE1 = (M_TI_ST_REPLY_METRES/M_TI_ST_REPLY_CHAINS),
            M_TI_ST_CHAIN_M_AVE1_AG = (M_TI_ST_CHAIN_METRES_AG/M_TI_ST_CHAINS_AG),
            M_TI_ST_REPLY_M_AVE1_AG = (M_TI_ST_REPLY_METRES_AG/M_TI_ST_REPLY_CHAINS_AG),

            MCBU_ST_CHAIN_M_AVE = (MCBU_ST_CHAIN_METRES/MCBU_ST_CHAINS),
            MCBU_ST_REPLY_M_AVE = (MCBU_ST_REPLY_METRES/MCBU_ST_REPLY_CHAINS),
            MCBU_ST_CHAIN_M_AVE_AG = (MCBU_ST_CHAIN_METRES_AG/MCBU_ST_CHAINS_AG),
            MCBU_ST_REPLY_M_AVE_AG = (MCBU_ST_REPLY_METRES_AG/MCBU_ST_REPLY_CHAINS_AG),

            MCBU_ST_CHAIN_M_AVE1 = (MCBU_ST_CHAIN_METRES/MCBU_ST_CHAINS),
            MCBU_ST_REPLY_M_AVE1 = (MCBU_ST_REPLY_METRES/MCBU_ST_REPLY_CHAINS),
            MCBU_ST_CHAIN_M_AVE1_AG = (MCBU_ST_CHAIN_METRES_AG/MCBU_ST_CHAINS_AG),
            MCBU_ST_REPLY_M_AVE1_AG = (MCBU_ST_REPLY_METRES_AG/MCBU_ST_REPLY_CHAINS_AG),

            WMBUTI_ST_CHAIN_M_AVE = (WMBUTI_ST_CHAIN_METRES/WMBUTI_ST_CHAINS),
            WMBUTI_ST_REPLY_M_AVE = (WMBUTI_ST_REPLY_METRES/WMBUTI_ST_REPLY_CHAINS),
            WMBUTI_ST_CHAIN_M_AVE_AG = (WMBUTI_ST_CHAIN_METRES_AG/WMBUTI_ST_CHAINS_AG),
            WMBUTI_ST_REPLY_M_AVE_AG = (WMBUTI_ST_REPLY_METRES_AG/WMBUTI_ST_REPLY_CHAINS_AG),

            WMBUTI_ST_CHAIN_M_AVE1 = (WMBUTI_ST_CHAIN_METRES/WMBUTI_ST_CHAINS),
            WMBUTI_ST_REPLY_M_AVE1 = (WMBUTI_ST_REPLY_METRES/WMBUTI_ST_REPLY_CHAINS),
            WMBUTI_ST_CHAIN_M_AVE1_AG = (WMBUTI_ST_CHAIN_METRES_AG/WMBUTI_ST_CHAINS_AG),
            WMBUTI_ST_REPLY_M_AVE1_AG = (WMBUTI_ST_REPLY_METRES_AG/WMBUTI_ST_REPLY_CHAINS_AG),

            A5070_ST_CHAIN_M_AVE = (A5070_ST_CHAIN_METRES/A5070_ST_CHAINS),
            A5070_ST_REPLY_M_AVE = (A5070_ST_REPLY_METRES/A5070_ST_REPLY_CHAINS),
            A5070_ST_CHAIN_M_AVE_AG = (A5070_ST_CHAIN_METRES_AG/A5070_ST_CHAINS_AG),
            A5070_ST_REPLY_M_AVE_AG = (A5070_ST_REPLY_METRES_AG/A5070_ST_REPLY_CHAINS_AG),

            D5070_ST_CHAIN_M_AVE = (D5070_ST_CHAIN_METRES/D5070_ST_CHAINS),
            D5070_ST_REPLY_M_AVE = (D5070_ST_REPLY_METRES/D5070_ST_REPLY_CHAINS),
            D5070_ST_CHAIN_M_AVE_AG = (D5070_ST_CHAIN_METRES_AG/D5070_ST_CHAINS_AG),
            D5070_ST_REPLY_M_AVE_AG = (D5070_ST_REPLY_METRES_AG/D5070_ST_REPLY_CHAINS_AG),

    ) %>%

    mutate(TIME_IN_FWD_HALF_PERC=      TIME_IN_ZONE    / (TIME_IN_ZONE_AG + TIME_IN_ZONE),
           TIME_IN_FWD_HALF_PERC_AG=   TIME_IN_ZONE_AG / (TIME_IN_ZONE_AG + TIME_IN_ZONE),
           TIME_IN_POSS_PERC=          TIME_IN_POSS    / (TIME_IN_POSS_AG + TIME_IN_POSS),
           TIME_IN_POSS_PERC_AG=       TIME_IN_POSS_AG / (TIME_IN_POSS_AG + TIME_IN_POSS)) %>%

    mutate (   TO_EXIT_WIDE_SKINNY_RATE           = TO_EXIT_WIDE_SKINNY/TO_EXIT_WIDE,
               TO_EXIT_WIDE_CORRIDOR_RATE         = TO_EXIT_WIDE_CORRIDOR/TO_EXIT_WIDE,
               TO_EXIT_WIDE_FAT_RATE              = TO_EXIT_WIDE_FAT/TO_EXIT_WIDE) %>%

    mutate (   TO_EXIT_WIDE_SKINNY_RATE_AG           = TO_EXIT_WIDE_SKINNY_AG/TO_EXIT_WIDE_AG,
               TO_EXIT_WIDE_CORRIDOR_RATE_AG          = TO_EXIT_WIDE_CORRIDOR_AG/TO_EXIT_WIDE_AG,
               TO_EXIT_WIDE_FAT_RATE_AG               = TO_EXIT_WIDE_FAT_AG/TO_EXIT_WIDE_AG) %>%

    mutate (   CLR_RET = CLR_CHAIN_KICK_RET/CLR,
               CLR_RET_AG = CLR_CHAIN_KICK_RET_AG/CLR_AG)

}
